CREATE TABLE IF NOT EXISTS meituan_ota_order_loss_monthly (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    hotel_id VARCHAR(64) NOT NULL,
    hotel_name VARCHAR(150) NOT NULL,
    business_date DATE NOT NULL COMMENT '近30天统计窗口结束日期',
    period_start_date DATE NOT NULL,
    period_end_date DATE NOT NULL,
    snapshot_time DATETIME NOT NULL,
    total_loss_order_count INT NOT NULL,
    total_loss_room_nights INT NOT NULL,
    total_loss_amount DECIMAL(14,2) NOT NULL,
    competitor_poi_id BIGINT NOT NULL,
    competitor_hotel_name VARCHAR(200) NOT NULL,
    competitor_star VARCHAR(40) NULL,
    competitor_score DECIMAL(6,2) NULL,
    competitor_lowest_price DECIMAL(12,2) NULL,
    competitor_distance_m INT NULL,
    competitor_circle_name VARCHAR(100) NULL,
    vip_tag TINYINT(1) NOT NULL DEFAULT 0,
    follow_status INT NULL,
    competitor_loss_order_count INT NOT NULL,
    competitor_loss_order_ratio_pct DECIMAL(8,4) NULL,
    competitor_loss_amount DECIMAL(14,2) NOT NULL,
    lost_room_types_text TEXT NULL,
    lost_room_types_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_meituan_order_loss_daily (hotel_id, business_date, competitor_poi_id),
    KEY idx_meituan_order_loss_date (hotel_id, business_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='美团近30天流失订单竞争酒店分析';
