CREATE TABLE IF NOT EXISTS meituan_ota_promotion_performance_30d (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    hotel_id VARCHAR(64) NOT NULL,
    period_start_date DATE NOT NULL,
    period_end_date DATE NOT NULL,
    snapshot_time DATETIME NOT NULL,
    plan_id BIGINT UNSIGNED NOT NULL,
    plan_name VARCHAR(255) NOT NULL,
    promotion_status VARCHAR(32) NOT NULL,
    launch_id BIGINT UNSIGNED NOT NULL,
    launch_name VARCHAR(255) NOT NULL,
    promotion_name VARCHAR(128) NOT NULL,
    promotion_type INT NULL,
    shop_id BIGINT UNSIGNED NULL,
    exposure_count INT NULL,
    click_count INT NULL,
    booking_order_count INT NULL,
    room_night_count INT NULL,
    booking_order_amount DECIMAL(14,2) NULL,
    spend_amount DECIMAL(14,2) NULL,
    cost_per_click DECIMAL(14,4) NULL,
    click_rate_pct DECIMAL(10,4) NULL,
    merchant_view_count INT NULL,
    cash_spend_amount DECIMAL(14,2) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_meituan_promotion_performance_day (hotel_id, period_end_date, plan_id, launch_id),
    KEY idx_meituan_promotion_performance_period (hotel_id, period_start_date, period_end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
