CREATE TABLE IF NOT EXISTS `bypms_room_status_snapshot` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `hotel_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hotel_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `source_platform` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '宝寓PMS',
  `business_date` date NOT NULL,
  `snapshot_time` datetime(6) NOT NULL,
  `snapshot_hour` datetime NOT NULL,
  `source_record_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `room_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `room_type_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `room_state` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `room_state_name` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sort_state` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `check_in` date NOT NULL,
  `check_out` date NOT NULL,
  `stay_nights` int DEFAULT NULL,
  `contract_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `channel` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `channel_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_type` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `booking_created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bypms_room_snapshot` (`hotel_id`,`snapshot_hour`,`source_record_id`),
  KEY `idx_bypms_room_date` (`hotel_id`,`business_date`),
  KEY `idx_bypms_room_state` (`hotel_id`,`business_date`,`room_state`),
  KEY `idx_bypms_room_id` (`hotel_id`,`room_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='宝寓PMS当日房态快照，不保存住客个人信息';
