CREATE TABLE IF NOT EXISTS `bypms_room_type_hourly_status` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `hotel_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hotel_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `source_platform` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '宝寓PMS',
  `business_date` date NOT NULL,
  `snapshot_time` datetime(6) NOT NULL,
  `snapshot_hour` datetime NOT NULL,
  `bypms_room_type_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `room_type_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_rooms` int NOT NULL DEFAULT 0,
  `empty_rooms` int NOT NULL DEFAULT 0,
  `living_rooms` int NOT NULL DEFAULT 0,
  `arrival_rooms` int NOT NULL DEFAULT 0,
  `departure_rooms` int NOT NULL DEFAULT 0,
  `saleable_rooms` int NOT NULL DEFAULT 0,
  `sold_rooms` int NOT NULL DEFAULT 0,
  `locked_rooms` int NOT NULL DEFAULT 0,
  `repair_rooms` int NOT NULL DEFAULT 0,
  `remaining_saleable_rooms` int NOT NULL DEFAULT 0,
  `occupancy_rate` decimal(9,4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bypms_room_type_hour` (`hotel_id`,`snapshot_hour`,`bypms_room_type_id`),
  KEY `idx_bypms_room_type_date` (`hotel_id`,`business_date`),
  KEY `idx_bypms_room_type_id` (`hotel_id`,`bypms_room_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='宝寓PMS房型当日库存小时快照';
