CREATE TABLE IF NOT EXISTS ctrip_ota_order_detail (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    hotel_id VARCHAR(64) NOT NULL,
    hotel_name VARCHAR(255) NOT NULL,
    platform_scope VARCHAR(20) NOT NULL,
    ctrip_hotel_id BIGINT NULL,
    form_id BIGINT UNSIGNED NOT NULL,
    order_id VARCHAR(64) NULL,
    order_source_type VARCHAR(32) NULL,
    ctrip_source_type VARCHAR(32) NULL,
    alliance_name VARCHAR(32) NULL,
    order_type VARCHAR(16) NULL,
    order_type_name VARCHAR(64) NULL,
    order_status_code INT NULL,
    order_status VARCHAR(100) NULL,
    order_status_type VARCHAR(32) NULL,
    booking_time DATETIME NULL,
    arrival_date DATE NOT NULL,
    departure_date DATE NULL,
    room_type_name TEXT NULL,
    room_quantity INT NULL,
    room_night_count INT NULL,
    guest_count INT NULL,
    currency VARCHAR(12) NULL,
    payment_type VARCHAR(16) NULL,
    payment_term VARCHAR(16) NULL,
    is_auto_confirmed TINYINT NULL,
    is_guaranteed TINYINT NULL,
    is_hour_room TINYINT NULL,
    is_credit_order TINYINT NULL,
    is_free_room_order TINYINT NULL,
    snapshot_time DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ctrip_order_detail (hotel_id, form_id),
    KEY idx_ctrip_order_arrival (hotel_id, arrival_date),
    KEY idx_ctrip_order_platform_arrival (platform_scope, arrival_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
