CREATE TABLE IF NOT EXISTS `ctrip_ota_flow_conversion_30d` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `hotel_id` VARCHAR(64) NOT NULL COMMENT '内部酒店 ID',
    `hotel_name` VARCHAR(255) NOT NULL,
    `platform_scope` VARCHAR(20) NOT NULL COMMENT 'ctrip 或 qunar',
    `ota_hotel_id` BIGINT NULL COMMENT '携程后台酒店 ID',
    `business_date` DATE NOT NULL,
    `period_start_date` DATE NOT NULL,
    `period_end_date` DATE NOT NULL,
    `snapshot_time` DATETIME NOT NULL,
    `app_visitors` BIGINT NULL COMMENT 'APP 访客量',
    `peer_app_visitors` BIGINT NULL COMMENT '竞争圈平均 APP 访客量',
    `list_exposure` BIGINT NULL COMMENT '列表页曝光量',
    `detail_exposure` BIGINT NULL COMMENT '详情页访客量',
    `exposure_to_detail_rate_pct` DECIMAL(9,4) NULL COMMENT '曝光转化率',
    `order_filling_count` BIGINT NULL COMMENT '订单页访客量',
    `order_submit_count` BIGINT NULL COMMENT '订单提交人数',
    `detail_to_order_rate_pct` DECIMAL(9,4) NULL COMMENT '下单转化率',
    `order_to_submit_rate_pct` DECIMAL(9,4) NULL COMMENT '成交转化率',
    `peer_list_exposure` BIGINT NULL COMMENT '竞争圈平均列表页曝光量',
    `peer_detail_exposure` BIGINT NULL COMMENT '竞争圈平均详情页访客量',
    `peer_exposure_to_detail_rate_pct` DECIMAL(9,4) NULL COMMENT '竞争圈平均曝光转化率',
    `peer_order_filling_count` BIGINT NULL COMMENT '竞争圈平均订单页访客量',
    `peer_order_submit_count` BIGINT NULL COMMENT '竞争圈平均订单提交人数',
    `peer_detail_to_order_rate_pct` DECIMAL(9,4) NULL COMMENT '竞争圈平均下单转化率',
    `peer_order_to_submit_rate_pct` DECIMAL(9,4) NULL COMMENT '竞争圈平均成交转化率',
    `list_exposure_peer_rank` INT NULL COMMENT '列表页曝光量竞争圈排名',
    `detail_exposure_peer_rank` INT NULL COMMENT '详情页访客量竞争圈排名',
    `order_filling_peer_rank` INT NULL COMMENT '订单页访客量竞争圈排名',
    `exposure_to_detail_rate_peer_rank` INT NULL COMMENT '曝光到详情转化率竞争圈排名',
    `detail_to_order_rate_peer_rank` INT NULL COMMENT '详情到订单页转化率竞争圈排名',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ctrip_flow_conversion_daily` (
        `hotel_id`, `platform_scope`
    ),
    KEY `idx_ctrip_flow_period_end` (`hotel_id`, `period_end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
