CREATE TABLE IF NOT EXISTS `ctrip_ota_promotion_performance_30d` (
    `hotel_id` VARCHAR(64) NOT NULL,
    `hotel_name` VARCHAR(255) NOT NULL,
    `platform_scope` VARCHAR(20) NOT NULL,
    `period_start_date` DATE NOT NULL,
    `period_end_date` DATE NOT NULL,
    `snapshot_time` DATETIME NOT NULL,
    `exposure_count` BIGINT NULL,
    `click_count` BIGINT NULL,
    `click_rate_pct` DECIMAL(10,2) NULL,
    `spend_amount` DECIMAL(14,2) NULL,
    `bonus_spend_amount` DECIMAL(14,2) NULL,
    `cash_spend_amount` DECIMAL(14,2) NULL,
    `cost_per_click` DECIMAL(14,4) NULL,
    `booking_order_count` BIGINT NULL,
    `booking_order_amount` DECIMAL(14,2) NULL,
    `room_night_count` BIGINT NULL,
    `conversion_rate_pct` DECIMAL(10,2) NULL,
    `return_on_ad_spend` DECIMAL(14,4) NULL,
    `avg_exposure_position` DECIMAL(10,2) NULL,
    `avg_click_position` DECIMAL(10,2) NULL,
    `ebk_order_count` BIGINT NULL,
    `other_order_count` BIGINT NULL,
    `data_delayed` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`hotel_id`, `platform_scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
