CREATE TABLE IF NOT EXISTS `meituan_price_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `task_id` VARCHAR(64) NULL,
    `hotel_id` VARCHAR(100) NOT NULL DEFAULT '',
    `hotel_name` VARCHAR(100) NOT NULL,
    `channel_source` VARCHAR(32) NOT NULL DEFAULT 'meituan',
    `room_type_id` VARCHAR(100) NULL,
    `room_type_name` VARCHAR(200) NOT NULL,
    `ota_room_type_id` VARCHAR(100) NULL,
    `ota_product_id` VARCHAR(100) NOT NULL,
    `ota_product_name` VARCHAR(200) NULL,
    `business_date` DATE NOT NULL,
    `current_sale_price` DECIMAL(10,2) NULL,
    `target_sale_price` DECIMAL(10,2) NOT NULL,
    `price_delta` DECIMAL(10,2) NULL,
    `price_delta_pct` DECIMAL(10,4) NULL,
    `execute_status` ENUM('PENDING', 'EXECUTING', 'SUCCESS', 'FAILED') NOT NULL DEFAULT 'PENDING',
    `review_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    `plugin_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    `verification_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    `source_decision_id` VARCHAR(128) NULL,
    `approval_id` VARCHAR(128) NULL,
    `created_by` VARCHAR(128) NULL,
    `approved_by` VARCHAR(128) NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `approved_at` DATETIME NULL,
    `queued_at` DATETIME NULL,
    `plugin_picked_at` DATETIME NULL,
    `executed_at` DATETIME NULL,
    `verified_at` DATETIME NULL,
    `platform_actual_price` DECIMAL(10,2) NULL,
    `verification_message` VARCHAR(512) NULL,
    `error_code` VARCHAR(64) NULL,
    `error_message` VARCHAR(1000) NULL,
    `retry_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `last_retry_at` DATETIME NULL,
    `payload_json` JSON NULL,
    `result_json` JSON NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_meituan_price_task_id` (`task_id`),
    KEY `idx_meituan_price_status` (`execute_status`),
    KEY `idx_meituan_price_workflow_status` (
        `review_status`, `plugin_status`, `verification_status`
    ),
    KEY `idx_meituan_price_hotel_id` (`hotel_id`),
    KEY `idx_meituan_price_hotel_date` (`hotel_name`, `business_date`),
    KEY `idx_meituan_price_product_date` (`ota_product_id`, `business_date`),
    KEY `idx_meituan_price_source_decision` (`source_decision_id`),
    KEY `idx_meituan_price_approval` (`approval_id`),
    KEY `idx_meituan_price_created_at` (`created_at`),
    KEY `idx_meituan_price_task_lookup` (
        `hotel_id`, `hotel_name`, `channel_source`, `ota_product_id`, `business_date`
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ctrip_price_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `task_id` VARCHAR(64) NULL,
    `hotel_id` VARCHAR(100) NOT NULL DEFAULT '',
    `hotel_name` VARCHAR(100) NOT NULL,
    `channel_source` VARCHAR(32) NOT NULL DEFAULT 'ctrip',
    `room_type_id` VARCHAR(100) NULL,
    `room_type_name` VARCHAR(200) NOT NULL,
    `ota_room_type_id` VARCHAR(100) NULL,
    `ota_product_id` BIGINT NOT NULL,
    `ota_product_name` VARCHAR(200) NULL,
    `rate_plan_name` VARCHAR(200) NULL,
    `business_date` DATE NOT NULL,
    `current_sale_price` DECIMAL(10,2) NULL,
    `target_sale_price` DECIMAL(10,2) NOT NULL,
    `price_delta` DECIMAL(10,2) NULL,
    `price_delta_pct` DECIMAL(10,4) NULL,
    `product_cipher` TEXT NOT NULL,
    `price_editable_flag` TINYINT(1) NULL,
    `is_hour_room` TINYINT(1) NOT NULL DEFAULT 0,
    `execute_status` ENUM('PENDING', 'EXECUTING', 'SUCCESS', 'FAILED') NOT NULL DEFAULT 'PENDING',
    `review_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    `plugin_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    `verification_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    `source_decision_id` VARCHAR(128) NULL,
    `approval_id` VARCHAR(128) NULL,
    `created_by` VARCHAR(128) NULL,
    `approved_by` VARCHAR(128) NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `approved_at` DATETIME NULL,
    `queued_at` DATETIME NULL,
    `plugin_picked_at` DATETIME NULL,
    `executed_at` DATETIME NULL,
    `verified_at` DATETIME NULL,
    `platform_actual_price` DECIMAL(10,2) NULL,
    `verification_message` VARCHAR(512) NULL,
    `error_code` VARCHAR(64) NULL,
    `error_message` VARCHAR(1000) NULL,
    `retry_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `last_retry_at` DATETIME NULL,
    `payload_json` JSON NULL,
    `result_json` JSON NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ctrip_price_task` (
        `hotel_id`, `hotel_name`, `channel_source`, `ota_product_id`, `business_date`
    ),
    UNIQUE KEY `uk_ctrip_price_task_id` (`task_id`),
    KEY `idx_ctrip_price_status` (`execute_status`),
    KEY `idx_ctrip_price_workflow_status` (
        `review_status`, `plugin_status`, `verification_status`
    ),
    KEY `idx_ctrip_price_hotel_id` (`hotel_id`),
    KEY `idx_ctrip_price_hotel_date` (`hotel_name`, `business_date`),
    KEY `idx_ctrip_price_product_date` (`ota_product_id`, `business_date`),
    KEY `idx_ctrip_price_source_decision` (`source_decision_id`),
    KEY `idx_ctrip_price_approval` (`approval_id`),
    KEY `idx_ctrip_price_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
